image: alpine/latest
packages:
  - pnpm
  - hut
  - git
oauth: pages.sr.ht/PAGES:RW
environment:
  site: skovati
tasks:
- build: |
    cd website
    pnpm install
    pnpm run build
    du -hs dist
- package: |
    tar -C website/dist -czvf $site.tgz .
- publish: |
    hut pages publish -d $site.dev $site.tgz
