image: alpine/latest
packages:
  - hugo
  - hut
oauth: pages.sr.ht/PAGES:RW
environment:
  site: skovati.srht.site
tasks:
- build: |
    cd website
    hugo
- package: |
    tar -C website/public -czvf $site.tgz .
- upload: |
    hut pages publish -d $site $site.tgz
