image: alpine/latest
packages:
  - hugo
  - hut
  - git
oauth: pages.sr.ht/PAGES:RW
environment:
  site: skovati.srht.site
tasks:
- build: |
    hugo -s website
- package: |
    tar -C website/public -czvf $site.tgz .
- publish: |
    hut pages publish -d $site $site.tgz
