image: alpine/latest
packages:
  - npm
  - hut
  - git
oauth: pages.sr.ht/PAGES:RW
environment:
  site: skovati.dev
tasks:
- build: |
    cd website
    npm install
    npm run build
    du -hs dist
- package: |
    tar -C website/dist -czvf $site.tgz .
- publish: |
    hut pages publish -d $site $site.tgz
