image: alpine/latest
packages:
  - hugo
oauth: pages.sr.ht/PAGES:RW
environment:
  site: skovati.srht.site
tasks:
- build: |
    cd website
    hugo
- package: |
    tar -C public -czvf site.tgz .
- upload: |
    acurl -f https://pages.sr.ht/publish/$site -Fcontent=@site.tgz
