baseURL = "https://skovati.dev/"
languageCode = "en-us"
title = "skovati"
theme = "smol"
relativeURLS = true
enableGitInfo = true

# Parameters
[params]
    subtitle = "a digital minimalist."
    dateFmt = "2006-01-02 15:04"

# Header
[menu]
    [[menu.main]]
        identifier = "articles"
        name = "articles"
        url = "/articles/"
        weight = 2

    [[menu.main]]
        identifier = "tags"
        name = "tags"
        url = "/tags/"
        weight = 3

# Footer
    [[menu.footer]]
        name = "content license"
        url = "https://creativecommons.org/licenses/by-nc-nd/4.0/legalcode.txt"
        weight = 2

    [[menu.footer]]
        name = "source code"
        url = "https://github.com/skovati/website"
        weight = 3

    [[menu.footer]]
        name = "email"
        url = "mailto:mail@skovati.dev"
        weight = 4

    [[menu.footer]]
        name = "pgp"
        url = "https://skovati.dev/pgp"
        weight = 5
