name = "smol"
license = "MIT"
licenselink = "https://github.com/skovati/website/blob/master/themes/smol/LICENSE"
description = "Minimal Hugo theme using a Monospace font and without any tracking or external dependencies."
homepage = "https://github.com/skovati/website"
min_version = "0.20"

[author]
  name = "skovati"
  homepage = "https:/github.com/skovati/website"

[original]
  author = "Vimux"
  homepage = "https://github.com/Vimux"
  repo = "https://github.com/colorchestra/blank"
