#!/bin/sh

RED='\033[1;31m'
GRE='\033[0;32m'
YEL='\033[1;33m'
BLU='\033[0;34m'
MAG='\033[0;35m'
CYA='\033[0;36m'
NC='\033[0;37m'


echo "${RED}"

echo " ______     __  __     ______     __   __   ______     ______   __    ";
echo "/\  ___\   /\ \/ /    /\  __ \   /\ \ / /  /\  __ \   /\__  _\ /\ \   ";
echo "\ \___  \  \ \  _\"-.  \ \ \/\ \  \ \ \'/   \ \  __ \  \/_/\ \/ \ \ \  ";
echo " \/\_____\  \ \_\ \_\  \ \_____\  \ \__|    \ \_\ \_\    \ \_\  \ \_\ ";
echo "  \/_____/   \/_/\/_/   \/_____/   \/_/      \/_/\/_/     \/_/   \/_/ ";
echo "                                                                      ";

echo "${NC}"

date

echo "${YEL}
Node-----------------------------------
${NC}"
screenfetch
echo "${GRE}
Network--------------------------------
${NC}"
vnstat -i eno1
echo "
"
vnstat -i wg0

echo "
"
docker exec -it qbittorrent curl ifconfig.io

echo "${BLU}
CPU/Mem--------------------------------
${NC}"
iostat -ch | tail -n 4 | head -n 2

echo "
"
free -m

echo "${MAG}
Disks----------------------------------
${NC}"
iostat -h -m -d | tail -n 3 | head -n 2
echo "
"
lsblk

echo "
"
df -h --local -x tmpfs -x devtmpfs

echo "
"
zpool status tank

echo "
"
zfs list

echo "${CYA}
Docker---------------------------------
${NC}"
docker stats --no-stream

echo "${RED}
Nas------------------------------------
${NC}"
ssh nas screenfetch
echo "${GRE}
Network--------------------------------
${NC}"
ssh nas vnstat -i eno1

echo "
"

echo "${BLU}
Cpu/Mem--------------------------------
${NC}"
ssh nas iostat -hc | tail -n 5 | head -n 3

echo "
"
ssh nas free -m

echo "${MAG}
Disks----------------------------------
${NC}"
ssh nas iostat -h -m -d | tail -n 7 | head -n 4

echo "
"
ssh nas lsblk

echo "
"
ssh nas df -h --local -x tmpfs -x devtmpfs

echo "${CYA}
Docker---------------------------------
${NC}"
ssh nas docker stats --no-stream
