#!/bin/bash 

bash /home/skovati/docker/nginx/website/status/ansi | /home/skovati/.local/bin/ansi2html -f 24 -s solarized -t "Skovati Network Status" -W > /home/skovati/docker/nginx/website/status/index.html
