#!/bin/bash 

bash /home/skovati/code/docker/nginx/skovati.com/status/ansi | ansi2html -f 24 -s solarized -t "Skovati Network Status" -W > /home/skovati/code/docker/nginx/skovati.com/status/index.html
