name: "build hugo site, publish image"

on:
  push:
    branches: ["master"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.110.0
    steps:
      - name: install hugo
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: checkout
        uses: actions/checkout@v3

      - name: build with hugo
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          hugo --minify

      - name: store artifacts
        uses: actions/upload-artifact@v3
        with:
          name: public
          path: ./public

  package:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: checkout
        uses: actions/checkout@v3

      - name: load artifacts
        uses: actions/download-artifact@v3
        with:
          name: public
          path: ./public

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: generate image tag
        id: tag
        run: |
          sha="${GITHUB_SHA::7}"
          unix="$(date +%s)"
          echo "tag=$sha-$unix" >> $GITHUB_OUTPUT

      - name: build and push image
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.tag.outputs.tag }}
            ghcr.io/${{ github.repository }}:latest
